import { AlertTriangle, BarChart3, Check, FileText, Lightbulb, Target, Users } from "lucide-react";
import careerSenseLogo from "../../assets/logos/BlueLogo.png";

const DISCLAIMER = "This report is an indicative assessment designed to help improve resume-job alignment and ATS readiness. The score is not generated by, or representative of, the employer's actual Applicant Tracking System.";

const tone = (value = "") => {
  const text = String(value).toLowerCase();
  if (text.includes("strong") || text === "match" || text.includes("excellent")) return "green";
  if (text.includes("partial") || text.includes("moderate")) return "gold";
  return "red";
};

function Mark({ value }) {
  const variant = tone(value);
  return <span className={`basic-status basic-status-${variant}`}>{variant === "green" ? <Check size={11} /> : <AlertTriangle size={11} />} {value}</span>;
}

function Page({ number, title, subtitle, children, cover = false }) {
  return (
    <section className="basic-print-page">
      <header className="basic-print-header">
        <div className="basic-brand"><img src={careerSenseLogo} alt="CareerSense" /><div><strong>Career<span>Sense</span></strong><small>ATS Intelligence</small></div></div>
        <div className="basic-header-meta"><p>Smarter Careers<br />Through Intelligence</p><small>Analyze&nbsp;&nbsp; | &nbsp;&nbsp;Insight&nbsp;&nbsp; | &nbsp;&nbsp;Advance</small></div>
      </header>
      {!cover && <div className="basic-page-heading"><h1>{title}</h1><p>{subtitle}</p></div>}
      <div className="basic-page-body">{children}</div>
      <footer className="basic-print-footer"><div className="basic-brand basic-brand-small"><img src={careerSenseLogo} alt="" /><div><strong>Career<span>Sense</span></strong><small>ATS Intelligence</small></div></div><span>Prepared by CareerSense ATS Intelligence&nbsp;&nbsp; | &nbsp;&nbsp;Indicative assessment, not the employer ATS.</span><b>{number}</b></footer>
    </section>
  );
}

function Panel({ title, icon: Icon = FileText, children, cool = false, compact = false }) {
  return <section className={`basic-panel ${cool ? "basic-panel-cool" : ""} ${compact ? "basic-panel-compact" : ""}`}><h2><span><Icon size={18} /></span>{title}</h2>{children}</section>;
}

function Bullets({ items = [] }) {
  return <ul className="basic-bullets">{items.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul>;
}

function ScoreRing({ score, label = "Overall Score" }) {
  return <div className="basic-score-wrap"><div className="basic-score-ring" style={{ "--score": `${score * 3.6}deg` }}><div><strong>{score}</strong><span>/ 100</span></div></div>{label ? <small>{label}</small> : null}</div>;
}

function BasicATSPrintReport({ report }) {
  const r = report || {};
  const counts = r.requirement_counts || {};
  const keywordCounts = {
    matched: r.keywords?.matched?.length || 0,
    partial: r.keywords?.partial?.length || 0,
    missing: r.keywords?.missing?.length || 0,
  };
  const scoreTotals = (r.score_categories || []).reduce((result, row) => ({
    weight: result.weight + (Number(row.weight) || 0),
    score: result.score + (Number(row.score) || 0),
  }), { weight: 0, score: 0 });
  return (
    <div className="basic-report-document brand-type">
      <style>{STYLES}</style>

      <Page number={1} cover>
        <div className="basic-cover-title"><h1>ATS Compatibility Report</h1><p>{r.analysis_type === "resume_jd" ? "Resume vs Job Description Analysis" : "Resume ATS Readiness Analysis"}</p></div>
        <div className="basic-cover-summary">
          <div className="basic-candidate"><small>Candidate Name</small><strong>{r.candidate_name}</strong><hr /><small>Target Role</small><strong>{r.target_role}</strong></div>
          <ScoreRing score={r.overall_score || 0} />
          <div className="basic-verdict"><Mark value={r.verdict} /><small>Verdict</small></div>
        </div>
        <Panel title="Executive Summary"><Bullets items={r.executive_summary} /></Panel>
        <div className="basic-stat-grid"><div><small>Compatibility</small><strong>{r.verdict}</strong></div><div><small>ATS Shortlist Probability</small><strong>{r.shortlist_outlook}</strong></div><div><small>Best Fit Today</small><strong>{r.best_fit_today}</strong></div><div><small>Critical Requirement Match</small><strong>{r.critical_match_percent || 0}%</strong></div><div><small>Core Keyword Coverage</small><strong>{r.keyword_coverage_percent || 0}%</strong></div></div>
        <Panel title="Report Snapshot" icon={BarChart3} cool><p><b>Primary Strengths</b> &nbsp; {r.primary_strengths?.join(", ")}</p><p><b>Primary Risk</b> &nbsp; {r.primary_risk}</p></Panel>
      </Page>

      <Page number={2} title="ATS Score Breakdown" subtitle={`How the overall score of ${r.overall_score || 0} / 100 was calculated`}>
        <div className="basic-score-banner"><BarChart3 /><b>Overall ATS Match Score:</b><strong>{r.overall_score} / 100</strong><Mark value={r.verdict} /></div>
        <Panel title="Score Breakdown">
          <table><thead><tr><th>Category</th><th>Weight</th><th>Score</th><th>Assessment</th></tr></thead><tbody>{r.score_categories?.map((row, i) => <tr key={i}><td>{row.category}</td><td>{row.weight}</td><td><b>{row.score}</b></td><td><Mark value={row.assessment} /></td></tr>)}</tbody><tfoot><tr><td><b>Total</b></td><td><b>{scoreTotals.weight} / 100</b></td><td><b>{scoreTotals.score} / 100</b></td><td><Mark value={r.verdict} /></td></tr></tfoot></table>
        </Panel>
        <div className="basic-score-facts"><span><small>Raw Score</small><b>{r.raw_score ?? r.overall_score}</b></span><span><small>Critical Requirement Match</small><b>{r.critical_match_percent || 0}%</b></span><span><small>Final Score After Safeguards</small><b>{r.overall_score || 0} / 100</b></span></div>
        <Panel title="Interpretation" icon={Lightbulb}><Bullets items={r.score_interpretation} /></Panel>
        <div className="basic-legend"><b>Assessment Legend</b><span className="basic-status-green">● Strong</span><span className="basic-status-gold">● Partial / Weak</span><span className="basic-status-red">● Critical Gap</span></div>
      </Page>

      <Page number={3} title="Mandatory Requirement Check" subtitle="JD requirements vs resume evidence">
        <table className="basic-requirements"><thead><tr><th>Requirement</th><th>Priority</th><th>Resume Evidence</th><th>Status</th></tr></thead><tbody>{r.requirements?.map((row, i) => <tr key={i}><td><b>{row.requirement}</b></td><td>{row.priority}</td><td>{row.evidence}</td><td><Mark value={row.status} /></td></tr>)}</tbody></table>
        <div className="basic-counts"><span>Matched <b>{counts.matched || 0}</b></span><span>Partial <b>{counts.partial || 0}</b></span><span>Weak <b>{counts.weak || 0}</b></span><span>Missing <b>{counts.missing || 0}</b></span><span>Missing Critical <b>{counts.missingCritical || 0}</b></span></div>
        <Panel title="Assessment"><Bullets items={r.requirements_assessment} /></Panel>
      </Page>

      <Page number={4} title="Candidate Strengths & Transferable Skills" subtitle="Where the resume shows strong professional value">
        <div className="basic-card-grid">{r.strengths?.map((item, i) => <article key={i}><span className="basic-round"><BarChart3 size={21} /></span><div><h3>{item.title}</h3><p>{item.explanation}</p></div></article>)}</div>
        <Panel title="Evidence Highlights" cool><Bullets items={r.evidence_highlights} /></Panel>
        <Panel title="Why these matter" icon={Lightbulb}><Bullets items={r.strengths_relevance} /></Panel>
      </Page>

      <Page number={5} title="Critical Skill Gaps" subtitle="Main factors reducing alignment with the target role">
        <div className="basic-card-grid">{r.critical_gaps?.map((item, i) => <article key={i} className="basic-gap"><span className="basic-round basic-round-red"><AlertTriangle size={21} /></span><div><h3>{item.title}</h3><span className="basic-priority">Priority: {item.priority || "Important"}</span><p>{item.evidence}</p><Mark value={item.impact} /></div></article>)}</div>
        <Panel title="Bottom Line"><Bullets items={r.gap_bottom_line} /></Panel>
      </Page>

      <Page number={6} title="Keyword Coverage Analysis" subtitle="Matched, partial, and missing role keywords">
        <KeywordPanel title="Matched Keywords" items={r.keywords?.matched} variant="green" />
        <KeywordPanel title="Partial Match" items={r.keywords?.partial} variant="gold" />
        <KeywordPanel title="Missing High-Impact Keywords" items={r.keywords?.missing} variant="red" />
        <div className="basic-keyword-counts"><span>Matched Keywords <b>{keywordCounts.matched}</b></span><span>Partial Keywords <b>{keywordCounts.partial}</b></span><span>Missing High-Impact <b>{keywordCounts.missing}</b></span></div>
        <div className="basic-keyword-summary"><ScoreRing score={r.keyword_coverage_percent || 0} label="Estimated Core Keyword Coverage" /><Panel title="What this means" cool><Bullets items={r.keyword_interpretation} /></Panel></div>
      </Page>

      <Page number={7} title="Resume Quality & ATS Optimization Issues" subtitle="Improvements needed independent of role-specific skills">
        <Panel title="Resume Health Check" icon={BarChart3} cool compact>
          <table className="basic-health-table"><thead><tr><th>Check</th><th>Score</th><th>Status</th><th>Finding</th><th>Recommended Fix</th></tr></thead><tbody>{r.resume_health_checks?.map((item) => <tr key={item.key}><td><b>{item.label}</b></td><td><b>{item.score}/100</b></td><td><Mark value={item.status} /></td><td>{item.finding}</td><td>{item.recommendation}</td></tr>)}</tbody></table>
          <div className="basic-section-detection"><span><b>Detected sections</b> {r.detected_sections?.length ? r.detected_sections.join(", ") : "Not identified"}</span><span><b>Missing sections</b> {r.missing_sections?.length ? r.missing_sections.join(", ") : "None identified"}</span></div>
        </Panel>
        <Panel title="Priority Resume Issues" icon={AlertTriangle} compact>
          <table className="basic-issue-table"><thead><tr><th>#</th><th>Issue</th><th>What was found</th><th>Recommendation</th></tr></thead><tbody>{r.resume_issues?.map((item, i) => <tr key={i}><td><b>{i + 1}</b></td><td><b>{item.title}</b></td><td>{item.issue}</td><td>{item.recommendation}</td></tr>)}</tbody></table>
        </Panel>
        <Panel title="ATS Optimization Priority" icon={Target} cool compact><ol className="basic-priorities">{r.optimization_priorities?.map((item, i) => <li key={i}><b>{i + 1}</b>{item}</li>)}</ol></Panel>
      </Page>

      <Page number={8} title="Final Verdict & Recommended Action Plan" subtitle="Next steps for the strongest career positioning">
        <div className="basic-final-score"><div><small>Overall ATS Match Score</small><ScoreRing score={r.overall_score || 0} label="" /></div><div><small>Critical Requirement Match</small><strong>{r.critical_match_percent || 0}%</strong></div><div><small>Keyword Coverage</small><strong>{r.keyword_coverage_percent || 0}%</strong></div><div><small>Verdict</small><Mark value={r.verdict} /></div><div><small>Recruiter Outlook</small><strong>{r.recruiter_outlook}</strong></div></div>
        <Panel title="Best-Fit Roles Today" icon={Users}><div className="basic-role-grid">{r.best_fit_roles?.map((item, i) => <span key={i}>{item}</span>)}</div></Panel>
        <Panel title="Recommended Next Steps" icon={Target} cool><ol className="basic-steps">{r.next_steps?.map((item, i) => <li key={i}><b>{i + 1}</b>{item}</li>)}</ol></Panel>
        <Panel title="CareerSense Recommendation"><Bullets items={r.recommendations} /></Panel>
        <p className="basic-disclaimer">{DISCLAIMER}</p>
      </Page>
    </div>
  );
}

function KeywordPanel({ title, items = [], variant }) {
  return <Panel title={title}><div className={`basic-tags basic-tags-${variant}`}>{items?.map((item, i) => <span key={i}>{item}</span>)}</div></Panel>;
}

const STYLES = `
.basic-report-document{color:#12385a}.basic-print-page{position:relative;box-sizing:border-box;width:210mm;min-height:297mm;margin:0 auto 24px;padding:12mm 10mm 11mm;background:#fff;display:flex;flex-direction:column;gap:5mm;overflow:hidden;box-shadow:0 18px 55px rgba(8,43,72,.1)}.basic-print-page:before,.basic-print-page:after{content:"";position:absolute;right:-18mm;top:-13mm;width:62mm;height:25mm;border:2mm solid rgba(206,193,169,.2);border-radius:50%;transform:rotate(-20deg);pointer-events:none}.basic-print-page:after{right:-23mm;top:-7mm;width:68mm;border-color:rgba(133,157,177,.14)}
.basic-print-header{height:22mm;display:flex;justify-content:space-between;align-items:flex-start;border-bottom:1px solid #9cafbf;padding-bottom:4mm;position:relative;z-index:1}.basic-header-meta{display:flex;flex-direction:column;align-items:flex-end;gap:3mm}.basic-header-meta p{text-transform:uppercase;letter-spacing:.2em;font-size:8px;line-height:1.6;color:#536f8c;border-left:1px solid #8aa0b4;padding-left:8mm}.basic-header-meta small{text-transform:uppercase;letter-spacing:.24em;font-size:5.5px;font-weight:800;color:#31516d}.basic-brand{display:flex;align-items:center;gap:3mm}.basic-brand img{width:17mm;height:17mm;object-fit:contain}.basic-brand strong{display:block;font-size:22px;color:#073665;line-height:1}.basic-brand strong span{color:#c88812}.basic-brand small{display:block;text-transform:uppercase;letter-spacing:.3em;font-size:7px;margin-top:2mm;color:#365d82}.basic-brand-small img{width:8mm;height:8mm}.basic-brand-small strong{font-size:11px}.basic-brand-small small{font-size:4px;margin-top:1mm}
.basic-page-heading h1,.basic-cover-title h1{font-size:30px;font-weight:900;letter-spacing:-.04em;color:#073665;line-height:1.05}.basic-page-heading p,.basic-cover-title p{font-size:15px;color:#54708d;margin-top:1mm}.basic-cover-title{margin-top:5mm}.basic-page-body{display:flex;min-height:0;flex:1;flex-direction:column;gap:4mm}.basic-print-footer{margin-top:auto;border-top:1px solid #9cafbf;padding-top:2mm;display:flex;align-items:center;justify-content:space-between;color:#71869b;font-size:6px}.basic-print-footer>span{margin-left:auto;margin-right:5mm}.basic-cover-summary{display:grid;grid-template-columns:1.2fr .8fr .9fr;align-items:center;gap:8mm}.basic-candidate{display:flex;flex-direction:column;gap:1mm}.basic-candidate small,.basic-final-score small{color:#57718b;font-size:9px}.basic-candidate strong{font-size:20px;color:#0a3157}.basic-candidate hr{width:100%;border:0;border-top:1px solid #cfdae3;margin:2mm 0}.basic-score-wrap{display:flex;flex-direction:column;align-items:center;gap:2mm;text-align:center}.basic-score-wrap>small{text-transform:uppercase;letter-spacing:.16em;font-size:6px;font-weight:800;color:#536f8c}.basic-score-ring{--score:0deg;width:38mm;height:38mm;border-radius:50%;background:conic-gradient(#d09a2c var(--score),#dfe5eb 0);display:grid;place-items:center}.basic-score-ring>div{width:29mm;height:29mm;background:white;border-radius:50%;display:grid;place-content:center;text-align:center}.basic-score-ring strong{font-size:26px;color:#b7161c;line-height:1}.basic-score-ring span{font-size:12px;color:#60758d}.basic-verdict{display:flex;flex-direction:column;align-items:center;gap:2mm}.basic-verdict small{text-transform:uppercase;letter-spacing:.2em}.basic-panel{border:1px solid #e6dfd4;background:#fbf9f5;border-radius:4mm;padding:4mm}.basic-panel-cool{background:#eef4f8}.basic-panel h2{display:flex;align-items:center;gap:3mm;font-size:16px;font-weight:900;color:#073665;margin-bottom:3mm}.basic-panel h2>span,.basic-round{width:10mm;height:10mm;display:grid;place-items:center;border-radius:50%;background:#f6ecd7;color:#bd7b08;flex:none}.basic-bullets{display:grid;gap:2mm;font-size:10px;line-height:1.35}.basic-bullets li{display:flex;gap:3mm}.basic-bullets li:before{content:'•';color:#c98a16;font-size:15px;line-height:10px}.basic-stat-grid{display:grid;grid-template-columns:1fr 1fr 1.3fr .8fr .8fr;gap:2mm}.basic-stat-grid>div{border:1px solid #e3ddd3;border-radius:3mm;padding:3mm;display:flex;flex-direction:column;gap:1.5mm}.basic-stat-grid small{color:#58728b;font-size:7px}.basic-stat-grid strong{font-size:11px;color:#0b3156}.basic-panel p{font-size:9px;line-height:1.4;margin-top:2mm}.basic-panel p b{color:#0a3157}.basic-score-banner{display:grid;grid-template-columns:auto 1fr auto auto;align-items:center;gap:4mm;background:#fff1f0;border:1px solid #f1c9c7;border-radius:3mm;padding:4mm}.basic-score-banner strong{font-size:24px;color:#bd1218}.basic-score-facts,.basic-keyword-counts{display:grid;grid-template-columns:repeat(3,1fr);gap:2mm}.basic-score-facts span,.basic-keyword-counts span{display:flex;align-items:center;justify-content:space-between;gap:2mm;border-radius:2mm;background:#eef3f6;padding:2mm 3mm;font-size:7px}.basic-score-facts small{color:#58728b}.basic-score-facts b,.basic-keyword-counts b{color:#073665;font-size:9px}.basic-legend{display:grid;grid-template-columns:1.2fr repeat(3,1fr);align-items:center;gap:2mm;border-radius:2mm;background:#eef3f6;padding:2mm 3mm;font-size:7px}.basic-legend span{padding:1.5mm 2mm;border-radius:2mm;text-align:center;font-weight:800}.basic-status{display:inline-flex;align-items:center;justify-content:center;gap:1.5mm;border-radius:2mm;padding:2mm 3mm;font-size:8px;font-weight:800;white-space:nowrap}.basic-status-green{background:#e5f4e8;color:#147132}.basic-status-gold{background:#fff1d5;color:#9a6200}.basic-status-red{background:#fde7e6;color:#b8171c}table{width:100%;border-collapse:collapse;font-size:7.5px}th{background:#e9f0f5;color:#3b5a77;text-align:left;padding:2mm}td{padding:1.5mm 2mm;border-bottom:1px solid #dce5eb;vertical-align:middle}tfoot td{background:#edf3f7;color:#073665}.basic-requirements{font-size:6.7px}.basic-requirements td{padding:1.2mm}.basic-counts{display:grid;grid-template-columns:repeat(5,1fr);gap:2mm}.basic-counts span{background:#eef3f6;border-radius:2mm;padding:2mm;text-align:center;font-size:7.5px}.basic-card-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:4mm}.basic-card-grid article{display:flex;gap:4mm;border:1px solid #e3ddd3;border-radius:3mm;padding:4mm;min-height:31mm}.basic-card-grid h3{font-size:12px;color:#073665;font-weight:900;line-height:1.15}.basic-card-grid p{font-size:8.5px;color:#395a78;line-height:1.4;margin-top:2mm}.basic-round-red{background:#fde3e2;color:#b7191f}.basic-priority{display:inline-flex;margin-top:1.5mm;border-radius:999px;background:#fff0d2;padding:1mm 2mm;color:#98620a;font-size:6px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.basic-gap .basic-status{margin-top:2mm}.basic-tags{display:flex;flex-wrap:wrap;gap:2mm}.basic-tags span{padding:2mm 4mm;border-radius:999px;font-size:8px}.basic-tags-green span{background:#e3f1e7}.basic-tags-gold span{background:#fbedd1}.basic-tags-red span{background:#fde4e3}.basic-keyword-summary{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:5mm}.basic-keyword-summary .basic-score-ring{width:31mm;height:31mm}.basic-keyword-summary .basic-score-ring>div{width:24mm;height:24mm}.basic-keyword-summary .basic-score-ring strong{font-size:21px}.basic-issues article{min-height:37mm}.basic-priorities,.basic-steps{display:grid;gap:2mm}.basic-priorities li,.basic-steps li{display:flex;align-items:center;gap:3mm;font-size:9px}.basic-priorities b,.basic-steps b{display:grid;place-items:center;width:7mm;height:7mm;border-radius:50%;background:#c88912;color:white}.basic-final-score{display:grid;grid-template-columns:1.05fr .72fr .72fr .9fr 1.35fr;align-items:stretch;gap:0;background:#fbf9f5;border-radius:4mm;padding:3mm}.basic-final-score>div{display:flex;min-height:35mm;flex-direction:column;align-items:center;justify-content:center;gap:3mm;border-right:1px solid #d4dde4;padding:0 2mm}.basic-final-score>div:last-child{border:0}.basic-final-score>div>strong{text-align:center;font-size:11px}.basic-final-score .basic-score-ring{width:30mm;height:30mm}.basic-final-score .basic-score-ring>div{width:23mm;height:23mm}.basic-final-score .basic-score-ring strong{font-size:20px}.basic-role-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:2mm}.basic-role-grid span{display:grid;place-items:center;text-align:center;border:1px solid #e3ddd3;border-radius:2mm;min-height:20mm;font-size:8px;font-weight:800}.basic-disclaimer{margin-top:auto;background:#edf4f8;border-radius:2mm;padding:2.5mm;font-size:7px;color:#58738d}
.basic-panel-compact{padding:2.5mm}.basic-panel-compact h2{font-size:12px;margin-bottom:1.5mm}.basic-panel-compact h2>span{width:7mm;height:7mm}.basic-panel-compact h2 svg{width:13px;height:13px}.basic-health-table{table-layout:fixed;font-size:5.8px;line-height:1.2}.basic-health-table th,.basic-health-table td{padding:1mm 1.2mm}.basic-health-table th:nth-child(1){width:20%}.basic-health-table th:nth-child(2){width:10%}.basic-health-table th:nth-child(3){width:15%}.basic-health-table th:nth-child(4),.basic-health-table th:nth-child(5){width:27.5%}.basic-health-table .basic-status{padding:.8mm 1.2mm;font-size:5.3px;white-space:normal}.basic-section-detection{display:grid;grid-template-columns:1fr 1fr;gap:2mm;margin-top:1.5mm}.basic-section-detection span{border-radius:2mm;background:#fff;padding:1.5mm 2mm;font-size:5.8px;line-height:1.25}.basic-section-detection b{color:#073665}.basic-issue-table{table-layout:fixed;font-size:5.7px;line-height:1.2}.basic-issue-table th,.basic-issue-table td{padding:.9mm 1.2mm}.basic-issue-table th:nth-child(1){width:5%}.basic-issue-table th:nth-child(2){width:21%}.basic-issue-table th:nth-child(3),.basic-issue-table th:nth-child(4){width:37%}.basic-panel-compact .basic-priorities{grid-template-columns:repeat(3,1fr);gap:2mm}.basic-panel-compact .basic-priorities li{font-size:6.5px;align-items:flex-start}.basic-panel-compact .basic-priorities b{width:5mm;height:5mm;flex:none}
@media screen and (max-width:900px){.basic-print-page{width:100%;min-height:auto;padding:24px}.basic-cover-summary,.basic-final-score{grid-template-columns:1fr}.basic-card-grid{grid-template-columns:1fr}.basic-role-grid{grid-template-columns:repeat(2,1fr)}.basic-health-table,.basic-issue-table{table-layout:auto}.basic-panel-compact .basic-priorities{grid-template-columns:1fr}.basic-print-footer>span{display:none}}
@media print{.basic-report-document{background:white}.basic-print-page{width:210mm;height:297mm;min-height:297mm;margin:0;box-shadow:none;break-after:page;page-break-after:always}.basic-print-page:last-child{break-after:auto;page-break-after:auto}}
`;

export default BasicATSPrintReport;
