const sharedNoiseCards = [
  {
    id: "noise-salary",
    correctZoneId: null,
    difficulty: 4,
    kind: "noise",
    preview: "Expected compensation: 32 LPA fixed, open to revision after joining bonus discussion.",
    why: "Compensation details do not belong on the resume.",
  },
  {
    id: "noise-references",
    correctZoneId: null,
    difficulty: 3,
    kind: "noise",
    preview: "References available upon request.",
    why: "This takes space without adding decision-making value.",
  },
  {
    id: "noise-objective",
    correctZoneId: null,
    difficulty: 4,
    kind: "noise",
    preview: "Seeking a challenging role in a dynamic organization where I can grow professionally.",
    why: "Generic objectives weaken the opening compared with a tailored summary.",
  },
  {
    id: "noise-hobbies",
    correctZoneId: null,
    difficulty: 5,
    kind: "noise",
    preview: "Hobbies include travelling, music, watching films, socializing, and exploring food.",
    why: "Long hobby lines are usually filler unless they support the role story.",
  },
  {
    id: "noise-address",
    correctZoneId: null,
    difficulty: 4,
    kind: "noise",
    preview: "Flat 11B, Cedar Residency, Lane 4, Phase 2, HSR Layout, Bengaluru 560102",
    why: "A full postal address is rarely needed on a modern one-page resume.",
  },
  {
    id: "noise-vague-impact",
    correctZoneId: null,
    difficulty: 5,
    kind: "noise",
    preview: "Worked with cross-functional teams on many important initiatives and delivered strategic value.",
    why: "This sounds impressive but says nothing measurable or specific.",
  },
];

export const resumeProfiles = [
  {
    id: "business-analyst",
    label: "Business Analyst Resume",
    accent: { primary: "#6ee7b7", secondary: "#fbbf24", tertiary: "#60a5fa" },
    headerGuide: "A business analyst resume should look structured, analytical, and keyword-rich.",
    zones: [
      { id: "identity", title: "Name", type: "header", lines: 1 },
      { id: "headline", title: "Title", type: "header", lines: 1 },
      { id: "contact", title: "Contact", type: "header", lines: 2 },
      { id: "photo", title: "Photo", type: "photo", lines: 1 },
      { id: "summary", title: "Summary", type: "body", lines: 3 },
      { id: "experience", title: "Experience", type: "body", lines: 5 },
      { id: "skills", title: "Skills", type: "body", lines: 3 },
      { id: "projects", title: "Projects", type: "body", lines: 4 },
      { id: "education", title: "Education", type: "body", lines: 2 },
    ],
    cards: [
      { id: "ba-name", correctZoneId: "identity", difficulty: 1, kind: "signal", preview: "Aarav Mehta" },
      { id: "ba-title", correctZoneId: "headline", difficulty: 1, kind: "signal", preview: "Senior Business Analyst" },
      { id: "ba-contact", correctZoneId: "contact", difficulty: 2, kind: "signal", preview: "Bengaluru, India • aarav.mehta@email.com • linkedin.com/in/aaravmehta" },
      { id: "ba-photo", correctZoneId: "photo", difficulty: 2, kind: "signal", preview: "Professional headshot with clean background", visual: "photo" },
      { id: "ba-summary", correctZoneId: "summary", difficulty: 2, kind: "signal", preview: "Business analyst with 6 years of experience translating stakeholder needs into process maps, dashboards, and product requirements for banking and retail teams." },
      { id: "ba-experience", correctZoneId: "experience", difficulty: 3, kind: "signal", preview: "Mapped a loan-origination workflow across 7 teams, cutting approval turnaround time by 22% after identifying 3 manual bottlenecks." },
      { id: "ba-skills", correctZoneId: "skills", difficulty: 2, kind: "signal", preview: "SQL, Power BI, Tableau, BRD/FRD, Jira, User Stories, Process Mapping, UAT, Excel" },
      { id: "ba-projects", correctZoneId: "projects", difficulty: 4, kind: "signal", preview: "Built a KPI exception dashboard for a lending ops team that reduced weekly reporting effort from 6 hours to 45 minutes." },
      { id: "ba-education", correctZoneId: "education", difficulty: 2, kind: "signal", preview: "MBA, Business Analytics — Christ University | B.Com — St. Xavier's College" },
      ...sharedNoiseCards.map((card) => ({ ...card, id: `ba-${card.id}` })),
    ],
  },
  {
    id: "software-developer",
    label: "Software Developer Resume",
    accent: { primary: "#67e8f9", secondary: "#a3e635", tertiary: "#f97316" },
    headerGuide: "A developer resume should surface code impact, stack clarity, and shipped work.",
    zones: [
      { id: "identity", title: "Name", type: "header", lines: 1 },
      { id: "headline", title: "Title", type: "header", lines: 1 },
      { id: "contact", title: "Contact", type: "header", lines: 2 },
      { id: "photo", title: "Photo", type: "photo", lines: 1 },
      { id: "summary", title: "Summary", type: "body", lines: 3 },
      { id: "experience", title: "Experience", type: "body", lines: 5 },
      { id: "skills", title: "Skills", type: "body", lines: 3 },
      { id: "projects", title: "Projects", type: "body", lines: 4 },
      { id: "education", title: "Education", type: "body", lines: 2 },
    ],
    cards: [
      { id: "sd-name", correctZoneId: "identity", difficulty: 1, kind: "signal", preview: "Neha Sinha" },
      { id: "sd-title", correctZoneId: "headline", difficulty: 1, kind: "signal", preview: "Full Stack Software Developer" },
      { id: "sd-contact", correctZoneId: "contact", difficulty: 2, kind: "signal", preview: "Pune, India • neha.sinha.dev@gmail.com • github.com/nehasinha • linkedin.com/in/nehasinha" },
      { id: "sd-photo", correctZoneId: "photo", difficulty: 2, kind: "signal", preview: "Professional headshot with clean background", visual: "photo" },
      { id: "sd-summary", correctZoneId: "summary", difficulty: 2, kind: "signal", preview: "Software developer with 5 years of experience building React, Node.js, and cloud-native products for high-volume customer workflows." },
      { id: "sd-experience", correctZoneId: "experience", difficulty: 3, kind: "signal", preview: "Optimized a billing API used by 2.3M monthly requests, reducing average response time from 420ms to 170ms." },
      { id: "sd-skills", correctZoneId: "skills", difficulty: 2, kind: "signal", preview: "React, Node.js, TypeScript, PostgreSQL, Redis, AWS, Docker, REST APIs, CI/CD" },
      { id: "sd-projects", correctZoneId: "projects", difficulty: 4, kind: "signal", preview: "Built a collaborative code review assistant with Next.js and OpenAI APIs that cut review turnaround by 34% for a student team." },
      { id: "sd-education", correctZoneId: "education", difficulty: 2, kind: "signal", preview: "B.Tech, Computer Science — VIT Vellore | AWS Certified Developer — Associate" },
      ...sharedNoiseCards.map((card) => ({ ...card, id: `sd-${card.id}` })),
    ],
  },
  {
    id: "ceo",
    label: "CEO Resume",
    accent: { primary: "#fca5a5", secondary: "#fde047", tertiary: "#86efac" },
    headerGuide: "An executive resume should feel concise, high-stakes, and outcome-driven.",
    zones: [
      { id: "identity", title: "Name", type: "header", lines: 1 },
      { id: "headline", title: "Title", type: "header", lines: 1 },
      { id: "contact", title: "Contact", type: "header", lines: 2 },
      { id: "photo", title: "Photo", type: "photo", lines: 1 },
      { id: "summary", title: "Executive Summary", type: "body", lines: 3 },
      { id: "experience", title: "Leadership Impact", type: "body", lines: 5 },
      { id: "skills", title: "Operating Strengths", type: "body", lines: 3 },
      { id: "projects", title: "Board Highlights", type: "body", lines: 4 },
      { id: "education", title: "Education", type: "body", lines: 2 },
    ],
    cards: [
      { id: "ceo-name", correctZoneId: "identity", difficulty: 1, kind: "signal", preview: "Rohan Kapoor" },
      { id: "ceo-title", correctZoneId: "headline", difficulty: 1, kind: "signal", preview: "Chief Executive Officer" },
      { id: "ceo-contact", correctZoneId: "contact", difficulty: 2, kind: "signal", preview: "Mumbai, India • rohan@kapoorventures.com • linkedin.com/in/rohankapoor" },
      { id: "ceo-photo", correctZoneId: "photo", difficulty: 2, kind: "signal", preview: "Professional executive portrait", visual: "photo" },
      { id: "ceo-summary", correctZoneId: "summary", difficulty: 2, kind: "signal", preview: "Growth-focused CEO with 14 years leading SaaS and commerce businesses through market expansion, fundraising, and operating model redesign." },
      { id: "ceo-experience", correctZoneId: "experience", difficulty: 3, kind: "signal", preview: "Scaled annual recurring revenue from $11M to $43M in 3 years while expanding into 4 new international markets." },
      { id: "ceo-skills", correctZoneId: "skills", difficulty: 2, kind: "signal", preview: "P&L Ownership, Fundraising, GTM Strategy, Org Design, Board Reporting, M&A, Pricing, Strategic Partnerships" },
      { id: "ceo-projects", correctZoneId: "projects", difficulty: 4, kind: "signal", preview: "Led a post-acquisition integration program that consolidated 3 product lines and improved gross margin by 9 points." },
      { id: "ceo-education", correctZoneId: "education", difficulty: 2, kind: "signal", preview: "MBA — INSEAD | B.E., Mechanical Engineering — BITS Pilani" },
      ...sharedNoiseCards.map((card) => ({ ...card, id: `ceo-${card.id}` })),
    ],
  },
  {
    id: "financial-analyst",
    label: "Financial Analyst Resume",
    accent: { primary: "#86efac", secondary: "#60a5fa", tertiary: "#f59e0b" },
    headerGuide: "A finance resume should communicate precision, models, and business decision support.",
    zones: [
      { id: "identity", title: "Name", type: "header", lines: 1 },
      { id: "headline", title: "Title", type: "header", lines: 1 },
      { id: "contact", title: "Contact", type: "header", lines: 2 },
      { id: "photo", title: "Photo", type: "photo", lines: 1 },
      { id: "summary", title: "Summary", type: "body", lines: 3 },
      { id: "experience", title: "Experience", type: "body", lines: 5 },
      { id: "skills", title: "Tools", type: "body", lines: 3 },
      { id: "projects", title: "Modeling Highlights", type: "body", lines: 4 },
      { id: "education", title: "Education", type: "body", lines: 2 },
    ],
    cards: [
      { id: "fa-name", correctZoneId: "identity", difficulty: 1, kind: "signal", preview: "Ishita Nair" },
      { id: "fa-title", correctZoneId: "headline", difficulty: 1, kind: "signal", preview: "Financial Analyst" },
      { id: "fa-contact", correctZoneId: "contact", difficulty: 2, kind: "signal", preview: "Gurugram, India • ishita.nair@financepro.com • linkedin.com/in/ishitanair" },
      { id: "fa-photo", correctZoneId: "photo", difficulty: 2, kind: "signal", preview: "Professional analyst headshot", visual: "photo" },
      { id: "fa-summary", correctZoneId: "summary", difficulty: 2, kind: "signal", preview: "Financial analyst experienced in FP&A, variance analysis, and forecasting for consumer and enterprise business units." },
      { id: "fa-experience", correctZoneId: "experience", difficulty: 3, kind: "signal", preview: "Built a rolling revenue forecast model that improved quarterly prediction accuracy from 81% to 94% across 5 product categories." },
      { id: "fa-skills", correctZoneId: "skills", difficulty: 2, kind: "signal", preview: "Excel, PowerPoint, SQL, Financial Modeling, Budgeting, Forecasting, Power BI, Variance Analysis, SAP" },
      { id: "fa-projects", correctZoneId: "projects", difficulty: 4, kind: "signal", preview: "Developed a pricing sensitivity model used by leadership to evaluate a 3-market expansion scenario worth $8M in projected revenue." },
      { id: "fa-education", correctZoneId: "education", difficulty: 2, kind: "signal", preview: "B.Com (Hons.) — Shri Ram College of Commerce | CFA Level II Candidate" },
      ...sharedNoiseCards.map((card) => ({ ...card, id: `fa-${card.id}` })),
    ],
  },
  {
    id: "doctor",
    label: "Doctor Resume",
    accent: { primary: "#5eead4", secondary: "#fda4af", tertiary: "#93c5fd" },
    headerGuide: "A medical resume should feel credible, calm, and tightly structured around patient impact.",
    zones: [
      { id: "identity", title: "Name", type: "header", lines: 1 },
      { id: "headline", title: "Title", type: "header", lines: 1 },
      { id: "contact", title: "Contact", type: "header", lines: 2 },
      { id: "photo", title: "Photo", type: "photo", lines: 1 },
      { id: "summary", title: "Clinical Profile", type: "body", lines: 3 },
      { id: "experience", title: "Clinical Experience", type: "body", lines: 5 },
      { id: "skills", title: "Core Skills", type: "body", lines: 3 },
      { id: "projects", title: "Research & Training", type: "body", lines: 4 },
      { id: "education", title: "Education", type: "body", lines: 2 },
    ],
    cards: [
      { id: "dr-name", correctZoneId: "identity", difficulty: 1, kind: "signal", preview: "Dr. Sana Qureshi" },
      { id: "dr-title", correctZoneId: "headline", difficulty: 1, kind: "signal", preview: "Internal Medicine Specialist" },
      { id: "dr-contact", correctZoneId: "contact", difficulty: 2, kind: "signal", preview: "New Delhi, India • drsanaq@gmail.com • linkedin.com/in/drsanaq" },
      { id: "dr-photo", correctZoneId: "photo", difficulty: 2, kind: "signal", preview: "Professional physician portrait", visual: "photo" },
      { id: "dr-summary", correctZoneId: "summary", difficulty: 2, kind: "signal", preview: "Internal medicine physician with 8 years of hospital experience managing acute care, chronic disease pathways, and resident teaching." },
      { id: "dr-experience", correctZoneId: "experience", difficulty: 3, kind: "signal", preview: "Managed 25+ inpatients per shift in a tertiary care unit while improving discharge documentation turnaround by 30%." },
      { id: "dr-skills", correctZoneId: "skills", difficulty: 2, kind: "signal", preview: "Acute Care, EMR Documentation, Patient Counseling, Clinical Audits, ICU Coordination, Case Review, Resident Mentorship" },
      { id: "dr-projects", correctZoneId: "projects", difficulty: 4, kind: "signal", preview: "Co-authored a diabetes care pathway study and implemented a follow-up checklist that reduced missed post-discharge reviews." },
      { id: "dr-education", correctZoneId: "education", difficulty: 2, kind: "signal", preview: "MD, Internal Medicine — AIIMS New Delhi | MBBS — King George's Medical University" },
      ...sharedNoiseCards.map((card) => ({ ...card, id: `dr-${card.id}` })),
    ],
  },
];

export const scoreBands = [
  { min: 0, title: "Booting", message: "Scanning structure." },
  { min: 420, title: "Signal Reader", message: "Good ATS instincts." },
  { min: 850, title: "Arena Master", message: "Clean, sharp, recruiter-ready." },
];
